/*
 * S2S RNG API
 *
 * Szrek2Solutions Random Number Generator API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Draw personnel to be included in the draw reports. The first user is the Draw Manager, second user is the Draw Auditor, and third is the Draw Observer.
    /// </summary>
    [DataContract]
    public partial class DrawUsers : IEquatable<DrawUsers>
    { 
        /// <summary>
        /// Full name of the user as it should appear in the draw reports
        /// </summary>
        /// <value>Full name of the user as it should appear in the draw reports</value>
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// If included, the login time for the user will appear in the draw reports
        /// </summary>
        /// <value>If included, the login time for the user will appear in the draw reports</value>
        [DataMember(Name="loginTime")]
        public DateTime? LoginTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DrawUsers {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  LoginTime: ").Append(LoginTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DrawUsers)obj);
        }

        /// <summary>
        /// Returns true if DrawUsers instances are equal
        /// </summary>
        /// <param name="other">Instance of DrawUsers to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DrawUsers other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    LoginTime == other.LoginTime ||
                    LoginTime != null &&
                    LoginTime.Equals(other.LoginTime)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (LoginTime != null)
                    hashCode = hashCode * 59 + LoginTime.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DrawUsers left, DrawUsers right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DrawUsers left, DrawUsers right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
