openapi: 3.0.0
info:
  title: S2S TRANSACTION API
  version: 1.0.0
  description: Szrek2Solutions Trusted Transactions API
  contact:
    url: 'http://www.szrek.com'
servers:
  - url: 'http://localhost:55002/s2s-transaction-api/v1.0'
components:
  schemas:
    UserData:
      title: UserData
      type: array
      description: Optional data fields that are signed and logged. They can also be extracted and used in post-processing and reports.
      items:
        type: string
      x-examples:
        example-1:
          - myfieldvalue1
          - myfieldvalue2
          - '123456'
    Status:
      title: Status
      type: object
      description: Status code and description
      properties:
        code:
          type: integer
          description: Numeric error or status code
          example: 0
        description:
          type: string
          description: Short description of the error or status code
          example: Success
    FieldError:
      title: FieldError
      type: object
      description: Details about a specific field error
      properties:
        code:
          type: string
          description: Error code name
        message:
          type: string
          description: Additional detail about the error code
        fieldName:
          type: string
          description: 'Name of the field that caused the error, if applicable'
        path:
          type: string
          description: 'Path to the field that caused the error, if applicable'
    ErrorResponse:
      description: Describes the error and any specific problems with fields in the request.
      allOf:
        - $ref: '#/components/schemas/Status'
        - type: object
          properties:
            fieldErrors:
              type: array
              items:
                $ref: '#/components/schemas/FieldError'
      x-examples:
        example-1:
          code: 999
          description: Input validation failed
          fieldErrors:
            - code: INVALID_VALUE
              message: Product not found
              fieldName: productId
              path: 'drawRequests[1].productId'
    BatchRequest:
      title: BatchRequest
      type: object
      properties:
        clientTransactionId:
          type: integer
          description: Client's unique ID for this transaction
          format: int64
          example: 102030450
        clientBusinessDay:
          type: integer
          description: Client's current business day. Format is YYMMDD.
          example: 200930
    StoreRequest:
      title: TransactionRequest
      type: object
      properties:
        clientRecordId:
          type: string
          description: Client's unique identifier for this record
          example: RQID-31234545-32
        userData:
          $ref: '#/components/schemas/UserData'
    BatchResponse:
      title: BatchResponse
      type: object
      properties:
        clientTransactionId:
          type: integer
          description: Client's unique ID for this transaction
          format: int64
          example: 102030450
        status:
          $ref: '#/components/schemas/Status'
        serverId:
          type: string
          example: RNG-TEST-87
          description: Transaction server identifier
        serverVersion:
          type: string
          example: '9.3'
          description: Transaction server version number
        businessDay:
          type: integer
          description: Business day under which the transaction was recorded. Format is YYMMDD.
          example: 200930
    StoreResult:
      title: StoreResult
      type: object
      properties:
        clientRecordId:
          type: string
          description: Client's unique identifier for this record
          example: RQID-31234545-32
        status:
          $ref: '#/components/schemas/Status'
        recordId:
          type: string
          description: Unique record identifier for the stored record
          example: EX191109870000000125
        recordHandle:
          type: integer
          description: Handle that can optionally be used for faster retrieval
          format: int64
        transactionTime:
          type: string
          format: date-time
          description: Timestamp of the stored record
          example: '2020-09-30T18:30:23Z'
      required:
        - status
    SecurityModule:
      title: SecurityModule
      type: object
      description: 'Details about the cryptographic Hardware Security Module (HSM) '
      properties:
        serial:
          type: string
          description: Serial number of the device used
          example: 01000000F00019C8
        sequencer:
          type: integer
          description: Sequence number assigned by the device
          example: 734595
        time:
          type: string
          description: Real-time clock value at the time of signing
          example: '2020-09-30T18:30:23Z'
        keyId:
          type: string
          description: Identifier of the key pair currently in use on the HSM
          example: 308C-1328-3940-DC32
    StoredRecord:
      title: StoredRecord
      type: object
      properties:
        clientRecordId:
          type: string
          description: Client's unique identifier for this record
          example: RQID-31234545-32
        status:
          $ref: '#/components/schemas/Status'
        recordId:
          type: string
          description: Unique record identifier for the stored record
          example: EX191109870000000125
        transactionTime:
          type: string
          format: date-time
          description: Timestamp of the stored record
          example: '2020-09-30T18:30:23Z'
        userData:
          $ref: '#/components/schemas/UserData'
  responses:
    BadRequestResponse:
      description: Bad Request
      headers: {}
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Example:
              value:
                code: 999
                description: Input validation failed
                fieldErrors:
                  - code: INVALID_VALUE
                    message: Product not found
                    fieldName: productId
                    path: 'drawRequests[1].productId'
paths:
  /transactions:
    post:
      summary: Store a Transaction
      operationId: post-transactions
      description: Sign and store a transaction in the block chain file.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BatchResponse'
                  - type: object
                    properties:
                      results:
                        type: array
                        description: 'Array of results records, corresponding to the array of requests'
                        items:
                          allOf:
                            - $ref: '#/components/schemas/StoreResult'
              examples: {}
        '400':
          $ref: '#/components/responses/BadRequestResponse'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/BatchRequest'
                - type: object
                  properties:
                    storeRequests:
                      description: One or more record store requests to be processed
                      type: array
                      items:
                        allOf:
                          - $ref: '#/components/schemas/StoreRequest'
                  required:
                    - storeRequests
            examples: {}
      parameters: []
      tags:
        - Transactions
    parameters: []
  /server-status:
    get:
      summary: Server Status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  serverId:
                    type: string
                    example: RNG-TEST-87
                    description: Transaction server identifier
                  serverVersion:
                    type: string
                    example: '9.3'
                    description: Transaction server version number
                  serverTime:
                    type: string
                    format: date-time
                    example: '2020-09-30T18:30:23Z'
                    description: Current system time of the transaction server
                  businessDay:
                    type: integer
                    description: Current business day for this transaction server. Format is YYMMDD.
                    example: 200930
                  cards:
                    type: array
                    description: Status of the configured Lynks HSM cards
                    items:
                      type: object
                      properties:
                        slot:
                          type: integer
                          description: Slot number of the HSM card
                        active:
                          type: boolean
                          description: Indicates the currently active HSM card
                        status:
                          type: string
                          description: Current status description for this card
                        serial:
                          type: string
                          description: Serial number of the HSM
                          example: 01000000F00019C8
                        sequencer:
                          type: integer
                          description: Current value of the HSM card's sequencer
                        lastErrorCode:
                          description: 'The error code of the most recent card error, if any'
                          type: integer
                        lastErrorTime:
                          type: string
                          description: 'The time of the last error code, if any'
                          format: date-time
                        keyId:
                          type: string
                          description: Identifier of the key pair currently in use on the HSM
                          format: binary
                          example: 08C-1328-3940-DC32
              examples:
                Example 1:
                  value:
                    serverId: RNG-TEST-87
                    serverVersion: '9.3'
                    serverTime: '2020-09-30T18:30:23Z'
                    businessDay: 200930
                    products:
                      - id: 1001
                        name: Cool3
                        type: INTEGER
                        requestCount: 1
                        lastRequestTime: '2019-08-24T14:15:22Z'
                      - id: 1002
                        name: Lotto6
                        type: INTEGER
                        requestCount: 1
                        lastRequestTime: '2019-08-24T14:15:22Z'
                    cards:
                      - slot: 0
                        active: true
                        status: OK
                        serial: 01000000F00019C8
                        sequencer: 18394549
                        lastError: 5
                        lastErrorTime: '2019-08-24T14:15:22Z'
                        keyId: 308C-1328-3940-DC32
                      - slot: 1
                        active: false
                        status: OK
                        serial: 01000000F00019C5
                        sequencer: 39459
                        keyId: 308C-1328-3940-DC32
      operationId: get-server-status
      description: Get current status of the transaction server.
      tags:
        - Status
    parameters: []
  /transactions/verification:
    get:
      summary: Verify Stored Transaction
      tags:
        - Transactions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  record:
                    $ref: '#/components/schemas/StoredRecord'
                  hsm:
                    $ref: '#/components/schemas/SecurityModule'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '404':
          description: Not Found
      operationId: get-transactions-verification
      description: Retrieves and verifies a previously stored record. Parameter MUST include one of either unique-record-id or client-record-id.
      parameters:
        - schema:
            type: string
          in: query
          name: unique-record-id
          description: Search using the Unique Record Identifier (URI) returned in the store response
        - schema:
            type: string
          in: query
          name: client-record-id
          description: Search using the clientRecordId sent in the store request
security: []
tags:
  - name: Status
  - name: Transactions
